### ISSUE TITLE
thin film color

### ISSUE THREAD

**Issue by Prof-LeBlanc** [quothbonney/TUDEL#24]
![WIN_20220920_09_42_25_Pro](https://user-images.githubusercontent.com/114007380/191297366-91994bc1-c333-4711-b01f-7c9767815436.jpg)
Thin films of PEDOT (like the image attached) are not registering as PEDOT after calibration. Doing analysis on them gives strange values. I'm thinking it just needs a bit of a tweak to the hue filter applied for the PEDOT

**Comment by quothbonney** [comment]
If the lighting consistency can be guaranteed, I would advise simply forgoing the calibration step. Calibration is a destructive procedure that does introduce artifacts. The calibration filter is automatically calculated based on the color of the tape. If calibration is absolutely essential, make sure there is an excess of light, as the brightness increase is the most destructive procedure.
