### ISSUE TITLE
Hue data 

### ISSUE THREAD

**Issue by Prof-LeBlanc** [quothbonney/TUDEL#25]
Hi Jack, would it be possible to add a "hue" analysis to the program. Similar to the saturation and value analysis functions already in the program

**Comment by quothbonney** [comment]
Yes, that should be easily done. I'll try to have it by the end of the day.

**Comment by quothbonney** [comment]
I just implemented this functionality. Commiting it now. I also fixed an issue with the graphs. You might have noticed that the graphs all have "Saturation" as the axis. This should now be fixed.

**Comment by quothbonney** [comment]
You'll notice significantly improved graphs now with the correct axes as well as the addition of hue as an option under analysis. Thank you for the excellent suggestion! Please leave more issues when you need.

Update the repository with `git pull origin master` in the directory of the program. It should "just work" after that.

If you have any questions with updating, please leave them below.
